version: 2

project_name: git-pdm

builds:
  - id: git-pdm
    main: ./cmd/git-pdm
    binary: git-pdm
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

msis:
  - name: git-pdm
    product_name: Git PDM
    manufacturer: "Tomb01"
    upgrade_code: "{3cc98179-244b-40f0-828d-fd88e480987e}"
    version: "{{ .Version }}"
    icon_path: ./installer/icon.ico
    template: ./installer/templace.wxs

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
